# Generated by Django 6.0.7 on 2026-07-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=200)),
                ('ProfilePic', models.ImageField(upload_to='images/')),
                ('Institution', models.CharField(max_length=200)),
                ('Professor', models.CharField(max_length=100)),
            ],
        ),
    ]
