# Generated by Django 6.0.7 on 2026-07-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
