# Generated by Django 6.0.7 on 2026-07-22 10:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0002_user_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('WorkDone', models.TextField()),
                ('InTime', models.TimeField(default=django.utils.timezone.now)),
                ('OutTime', models.TimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='Record.user')),
            ],
        ),
    ]
