# Generated by Django 6.0.7 on 2026-07-22 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0003_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='InTime',
        ),
        migrations.RemoveField(
            model_name='data',
            name='OutTime',
        ),
        migrations.AlterField(
            model_name='data',
            name='WorkDone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='intime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='data',
            name='outtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
