# Generated by Django 6.0.7 on 2026-07-22 11:47

import Record.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0004_remove_data_intime_remove_data_outtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='intime',
        ),
        migrations.RemoveField(
            model_name='data',
            name='outtime',
        ),
        migrations.AddField(
            model_name='data',
            name='Intime',
            field=models.TimeField(default=Record.models.current_time),
        ),
        migrations.AddField(
            model_name='data',
            name='Outtime',
            field=models.TimeField(default=Record.models.current_time),
        ),
    ]
