# Generated by Django 6.0.7 on 2026-07-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0005_remove_data_intime_remove_data_outtime_data_intime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Intime',
            new_name='InTime',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Outtime',
            new_name='OutTime',
        ),
    ]
