# Generated by Django 6.0.7 on 2026-07-25 16:51

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0006_rename_intime_data_intime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ProfilePic',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/'),
        ),
    ]
